server:
  port: 7001

eureka:
  instance:
    # eureka服务器的实例名称
    hostname: eureka7001.com
  client:
    # false表示不向服务器注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心：职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # Eureka Server注册地址
      # 单机版本
      defaultZone: http://localhost:7001/eureka/
      # 集群版本，有几个server就写几个地址
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka